### ISSUE TITLE
Error messages in example

### ISSUE THREAD

**Issue by bschilder** [immunogenomics/IMPACT#1]
I just cloned the repo and tried running the first example, but received the following series of error messages. Part of the issue appears to stem from the fact that there's a number of dependencies. If so, could you please provide a list of IMPACT's dependencies in the beginning of the documentation? If I can get past some of these initial roadblocks, I look forward to using this tool. Thank you!:

`schilder:brians-mbp Training/$ ./Pipeline.sh "TF" "cell type" "number input (ChIP-seq) files"

First arg: TF
Second arg: cell type
Third arg: number input (ChIP-seq) files
./Pipeline.sh: line 5: module: command not found
Error in 1:as.numeric(args[3]) : NA/NaN argument
In addition: Warning message:
In as.numeric(args[3]) : NAs introduced by coercion
Execution halted
ls: *TF.*: No such file or directory
./Pipeline.sh: line 18: dos2unix: command not found
cp: TF.1.PWM.txt: No such file or directory
rm: TF.1.PWM.txt: No such file or directory
./Pipeline.sh: line 18: dos2unix: command not found
cp: TF.0.PWM.txt: No such file or directory
rm: TF.0.PWM.txt: No such file or directory
./Pipeline.sh: line 22: dos2unix: command not found
cp: AllTFs_PWM.txt: No such file or directory
rm: AllTFs_PWM.txt: No such file or directory
Can't open perl script "/data/srlab/amariuta/homer/bin/findMotifsGenome.pl": No such file or directory
Error in library(GenomicRanges) : 
  there is no package called ‘GenomicRanges’
Execution halted
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
Error in library(GenomicRanges) : 
  there is no package called ‘GenomicRanges’
Execution halted
cp: train_test_positive_bed.txt: No such file or directory
cp: train_test_negative_bed.txt: No such file or directory
[1] 1
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'train_test_positive_bed_TFonly_center.txt': No such file or directory
Execution halted
`

**Comment by TiffanyAmariuta** [comment]
Hello Brian, 

Thanks for your interest in our tool. 

Regarding your comments, it seems that you copy pasted "TF" "cell type" "number input (ChIP-seq) files" as arguments for Pipeline.sh. You must substitute the variable "TF" with the TF and "cell type" with the cell type you wish you model and "number input (ChIP-seq) files" with the number of ChIP-seq files you are providing, for example "Pipeline.sh Tbet Th1 1". As you can see, the script Pipeline.sh was looking for a numeric value for argument 3, not a character string: "Error in 1:as.numeric(args[3]) : NA/NaN argument". I've included some sample data in the Training directory so that users may run Pipeline.sh. As for the "module load R/3.2.2" line, this is how I specify my version of R in my linux environment. Please specify your version of R how you typically do so in linux. Furthermore, a motif finding software such as HOMER or MEME is required. Thank you for pointing out that this dependency should be specified.  

Best regards, 

Tiffany
