### ISSUE TITLE
LDSC baseline-LD custom set

### ISSUE THREAD

**Issue by bcrone** [immunogenomics/IMPACT#5]
Is a list of the set of 69 custom baseline-LD annotations available?
I am unable to find mention of this set in the repository or in annot files

**Comment by TiffanyAmariuta** [comment]
Hi Brad, 

Thanks for bringing this up! I've just added a text file containing the names of the 69 baselineLD annotations I've used in my analyses. Located at IMPACT/sLDSC/69_baselineLD_annotations.txt 

The original baselineLD model contained 73 annotations (https://alkesgroup.broadinstitute.org/LDSCORE/1000G_Phase3_baselineLD_ldscores.tgz), including T cell specific enhancers (called Vahedi super and typical enhancers). Since we were assessing the cell type specificity of our annotations, having cell type specific annotations in the baseline LD model would defeat that purpose. 

Hope this clears things up!
